baseurl: "https://stvpj.com/"
languageCode: en-us
theme: hugo-theme-stack
title: Steve's Blog
copyright: Steve

DefaultContentLanguage: en
hasCJKLanguage: false

languages:
  en:
    languageName: English
    title: Steve's Blog
    weight: 1
    params:
      sidebar:
        subtitle: Sharing thoughts on tech, projects, and the occasional rabbit hole.

services:
  disqus:
    shortname: ""
  googleAnalytics:
    id: G-XRPLQPWVHJ

pagination:
  pagerSize: 3

permalinks:
  post: /p/:slug/
  page: /:slug/

params:
  mainSections:
    - post
  featuredImageField: image
  rssFullContent: true

  favicon: /favicon.ico

  footer:
    since: 2024
    customText:

  dateFormat:
    published: Jan 02, 2006
    lastUpdated: Jan 02, 2006 15:04 MST

  sidebar:
    avatar:
      enabled: true
      local: true
      src: img/avatar.png

  article:
    math: false
    toc: true
    readingTime: true
    license:
      enabled: true
      default: Licensed under CC BY-NC-SA 4.0

  comments:
    enabled: false

  widgets:
    homepage:
      - type: search
      - type: archives
        params:
          limit: 5
      - type: categories
        params:
          limit: 10
      - type: tag-cloud
        params:
          limit: 10
    page:
      - type: toc

  opengraph:
    twitter:
      site:
      card: summary_large_image

  defaultImage:
    opengraph:
      enabled: false
      local: false
      src:

  colorScheme:
    toggle: true
    default: auto

  imageProcessing:
    cover:
      enabled: true
    content:
      enabled: true

menu:
  main: []

  social:
    - identifier: linkedin
      name: LinkedIn
      url: https://www.linkedin.com/in/stvpjames/
      params:
        icon: brand-linkedin

    - identifier: instagram
      name: Instagram
      url: https://www.instagram.com/stvpj/
      params:
        icon: brand-instagram

    - identifier: mastodon
      name: Mastodon
      url: https://mastodon.social/@Stvpj
      params:
        icon: brand-mastodon

    - identifier: bluesky
      name: Bluesky
      url: https://bsky.app/profile/stvpj.com
      params:
        icon: brand-bluesky

related:
  includeNewer: true
  threshold: 60
  toLower: false
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 200

markup:
  goldmark:
    extensions:
      passthrough:
        enable: true
        delimiters:
          block:
            - - \[
              - \]
            - - $$
              - $$
          inline:
            - - \(
              - \)
    renderer:
      unsafe: true
  tableOfContents:
    endLevel: 4
    ordered: true
    startLevel: 2
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    tabWidth: 4