[build]
  publish = "public"
  command = "hugo --cleanDestinationDir --buildFuture --buildDrafts=false"

[context.production.environment]
  HUGO_VERSION = "0.146.5"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"