backend:
  name: git-gateway
  branch: main
  login: true
  auth_type: pkce
  base_url: https://stvpj.com
  auth_endpoint: /.netlify/functions/auth

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "post"
    label: "Posts"
    folder: "content/post"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Date"
        name: "date"
        widget: "datetime"
      - label: "Body"
        name: "body"
        widget: "markdown"