backend:
  name: auth0
  domain: dev-okdrcvrv6dhxu542.auth0.com
  clientId: Rhz8LwFDYIxMZB7Jdey3FTGtgid2LdZZ
  login: true

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "post"
    label: "Posts"
    folder: "content/post"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }