backend:
  name: auth0
  app_id: ${AUTH0_CLIENT_ID}
  base_url: ${AUTH0_BASE_URL}
  auth_url: ${AUTH0_AUTH_URL}

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "post"
    label: "Posts"
    folder: "content/post"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }